version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/src/public
    user: '${UID}:${GID}'
    ports:
      - '80:80'
      - '443:443'
    restart: on-failure
    volumes:
      - ./:/var/www/html
